### ISSUE TITLE
How to start leap in local ?

### ISSUE THREAD

**Issue by securekim** [leapdao/leapdao-docs#12]
Actually, I am a newbie in plasma-leap. 

I understand the concept of plasma-leap, But I don't know how to run it in local.

You know, There are so many repos...

How can I run Testnet, contracts (bridge, operator, exitHandler), nodes, plasma EVM and web ?

I need this project and I want to start whole thing in local for test. Please help me.

**Comment by johannbarbie** [comment]
unfortunately the docs-maintainer role is currently not filled: https://app.glassfrog.com/roles/11164217
🤷‍♂️ what can we do? 😁

**Comment by johannbarbie** [comment]
> How can I run solEVM-enforcer with this?
solEVMenforcer is currently not integrated into contract or node yet. see issue here: https://github.com/leapdao/leap-contracts/issues/68

**Comment by securekim** [comment]
I just want to know how to start whole leap in local.
But It's not easy to me.. (maybe include other newbies.)
Anyway, I will find a way and write it for other newbies...Thank you guys !
