### ISSUE TITLE
Link for spending conditions example is broken

### ISSUE THREAD

**Issue by aerophile** [leapdao/leapdao-docs#24]
The link for the example of a spending condition mentioned [here](https://docs.leapdao.org/spending-conditions/) is broken. I think it should point to https://github.com/leapdao/spending-conditions/blob/master/contracts/SpendingCondition.sol . We can also remove the link from the text as well as the text says "You can find an example for a spending condition in our repositories" and just leave the link for "our repositories"

**Comment by troggy** [comment]
@aerophile thanks for reporting this!

**Comment by aerophile** [comment]
@troggy  happy to help, should I close this issue now that a pull request fixing this is there ?

**Comment by aerophile** [comment]
Closing Issue
